from .animal import Animal
from .snake import Snake
from .earthworms import Earthworms
from .leeches import Leeches
from .slug import Slugs
from .lizard import Lizard
from .dolphin import Dolphin
from .penguin import Penguin
from .seal import Seal
from .orca import Orca
from .whale import Whale
from .tiger import Tiger
from .wolf import Wolf
from .squirrel import Squirrel
from .buffalo import Buffalo
from .llama import Llama
